# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - rmou-gl-myfirstapp

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: rmou-gl-myfirstapp 
  AZURE_WEBAPP_PACKAGE_PATH: 'python-docs-hello-world' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Set up Python version ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip 
          pip install -r  ./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/requirements.txt

      - name: 'Building web app'
        uses: azure/appservice-build@v2
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
                
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}